### ISSUE TITLE
Store users and timer in some sort of local state

### ISSUE THREAD

**Issue by TravisBumgarner** [pluralsight/mob-timer#12]
When opening the mob timer after restarting, our names and the time we set is reset to the default.

**Comment by allan-stewart** [comment]
The timer _should_ already do this. It doesn't keep track of which mobber was next, but all the names should be retained. So if it's not working for you, then we've probably got a bug.

Can you give me more detail so we can try to track it down? Off-hand, I'm wondering if it's a file permissions problem -- maybe it cannot write the file? What OS, etc?

**Comment by parkerholladay** [comment]
I've noticed this before as well. I'm actually working on a change to the config right now. It is currently writing to `os.tempDir()`, but I'd like to change that to writing in the `homeDir()` instead, so it doesn't get lost on reboot from time to time.
