### ISSUE TITLE
Timer doesn't reset when user is disabled

### ISSUE THREAD

**Issue by TravisBumgarner** [pluralsight/mob-timer#19]
Steps to recreate:
1.  Pause timer on one person
2. Disable that person, automatically switches to next person
3. Timer doesn't reset

**Comment by TravisBumgarner** [comment]
Going to try and tackle this. I know nothing about Electron apps so I might give up shortly.

**Comment by allan-stewart** [comment]
I'm not sure how far you got on this @TravisBumgarner , but since it sounded like you were unsure about it and I had some time, I went ahead and created the above PR to fix the issue.
