### ISSUE TITLE
Allow the escalation timer to be configurable

### ISSUE THREAD

**Issue by joejag** [pluralsight/mob-timer#3]
It'd be good if the timer escalation feature was configurable. The culture in the mobs where I am is that you leave when the timer finishes, rather than be given a 30 second grace period to move over.

I've had an attempt at this over at https://github.com/joejag/mob-timer

I'd be happy to add this feature myself if it would be welcome? 

It looks like the internal model of this project is being changed at the moment to pull out domain concepts like the `mobbers.js`. I suppose it's best to hold off making a PR until that work is finished?

**Comment by mattcbaker** [comment]
@joejag We are in the throws of restructuring and enhancing the mob timer. We don't plan on it taking very long, but for the moment I'd hold off on the PR.

**Comment by joejag** [comment]
Hi @mattcbaker, that's great. I'll hold off for now.

**Comment by mattcbaker** [comment]
@joejag the ability to configure time escalation has been introduced with commit https://github.com/pluralsight/mob-timer/commit/06ca41a940ccbe6eac1ccab2a323575b87845f91

**Comment by joejag** [comment]
Thanks @mattcbaker
