### ISSUE TITLE
Mob Timer no longer showing up

### ISSUE THREAD

**Issue by ethanstrominger** [pluralsight/mob-timer#47]
Mob Timer is no longer showing up underneath the list of participants.  I tried re-installing VS Code, Liveshare, and Mob Timer, same issue.  I sent message to @mattcbaker in LinkedIn.

**Comment by allan-stewart** [comment]
See #48 ; I think we have a case of mistaken mob timers.

**Comment by ChuckBates** [comment]
You are correct Allan, this is an issue for the VS Code Extension mob timer, which is currently in preview and kept in a private repository. We hope to make that open source in the near future. If it helps, this issue of the mob timer not showing up has already been opened in the private repo. 

Closing issue as not for this repo.
