### ISSUE TITLE
Link from VSCode Extensions page for asking questions gives 404

### ISSUE THREAD

**Issue by ethanstrominger** [pluralsight/mob-timer#48]
Steps:
1. navigate to https://marketplace.visualstudio.com/items?itemName=pluralsight.live-share-mob-timer&ssr=false#qna
2. Click on Ask a Question or Github Repository link and I get a 404.

- URL when click on Github: https://github.com/ps-dev/liveshare-mob-timer/issues?utm_source=vsmp&utm_medium=ms%20web&utm_campaign=mpdetails and 
- URL when click on Ask a Question: https://github.com/ps-dev/liveshare-mob-timer/issues?utm_source=vsmp&utm_medium=ms%20web&utm_campaign=mpdetails

**Comment by ethanstrominger** [comment]
![image](https://user-images.githubusercontent.com/32078396/99970464-deefb700-2d69-11eb-9903-19668b05af7a.png)

**Comment by allan-stewart** [comment]
The mob timer for VS Code Live Share sessions is actually a different project from this repository. Pluralsight has many teams that do mob programming and apparently has shared multiple mob timers. I looked around and didn't find the source repository for the VS Code one.

This repo is for an electron-based, cross platform timer app that runs on a single machine.

**Comment by ChuckBates** [comment]
As Allan said, these issues are for our VS Code extension which is currently in preview and kept in a private repository. We hope to make that open source in the near future. This repo is for our open source desktop electron mob timer. 

Closing as not an issue for this repo
