### ISSUE TITLE
Open to a pull request adding prettier?

### ISSUE THREAD

**Issue by dignite** [pluralsight/mob-timer#9]
Hey! I love this application and I use it daily.

This weekend I started hacking away adding features that I have been wanting for a while with no thought of re-integrating, but maybe some of these changes could benefit everyone. An enabler to cherrypicking some of these things back into this repository would be prettier.

https://github.com/pluralsight/mob-timer/compare/master...dignite:master

Would you be open to me adding prettier to this project?

**Comment by allan-stewart** [comment]
I can see how consistent code formatting / a style guide / linting could make the code more consistent and therefore easier to merge specific changes back into the project. I would like that. However, `prettier` is a (self-admittedly) opinionated code formatter and it happens to use several conventions that run counter to the style that my coworkers tend to write. (For example, we tend to use single quotes and shun semicolons.)

So I'll ask around among those here at Pluralsight who have contributed to the mob-timer to see how they feel about this.

But no matter what we decide on this, I'm glad to hear that you enjoy the mob-timer! Hacking on the timer is one of the reasons we built it, so I hope it has been easy for you to understand and add your own features.

**Comment by dignite** [comment]
Great, eagerly awaiting feedback! Skipping semicolons and using single quotes would be possible:

- https://prettier.io/docs/en/options.html#semicolons
- https://prettier.io/docs/en/options.html#quotes

**Comment by parkerholladay** [comment]
I have not been a fan of prettier because of how opinionated it is. Though, I would love to build some style guide for the project through eslint that we can enforce with pre-commit hooks.

**Comment by allan-stewart** [comment]
Internally in our Slack channels I'm trying to solicit some feedback. Seems like we may be in favor of having something... just not sure yet if we prefer `prettier` or just `eslint`. Hoping to get a decision on this soonish.
